export default [
  {
    id: 0,
    image: '',
    title: 'Silver',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 1,
    image: '',
    title: 'Moonlighter',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 2,
    image: '',
    title: 'Legend of Zelda: Breath of the Wild',
    details: ['Fantasy', 'Action', 'Adventure'],
  },
  {
    id: 3,
    image: '',
    title: 'Commandos 2',
    details: ['WW2', 'Action', 'RTT'],
  },
  {
    id: 4,
    image: '',
    title: 'Apex Legends',
    details: ['Multiplayer', 'FPS'],
  },
  {
    id: 5,
    image: '',
    title: "Dragon's Dogma",
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 6,
    image: '',
    title: 'Valheim',
    details: ['Fantasy', 'Survival', 'Sandbox'],
  },
  {
    id: 7,
    image: '',
    title: 'The Elder Scrolls V: Skyrim',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 8,
    image: '',
    title: 'Divinity Original Sin 2',
    details: ['Fantasy', 'RPG'],
  },
  {
    id: 9,
    image: '',
    title: 'Darkest Dungeon',
    details: ['Fantasy', 'Roguelike', 'RPG'],
  },
  {
    id: 10,
    image: '',
    title: 'The Witcher 3: Wild Hunt',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 11,
    image: '',
    title: 'Dark Messiah of Might and Magic',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 12,
    image: '',
    title: 'Counter-Strike',
    details: ['Multiplayer', 'FPS'],
  },
  {
    id: 13,
    image: '',
    title: 'Fable',
    details: ['Fantasy', 'Action', 'RPG'],
  },
  {
    id: 14,
    image: '',
    title: 'Far Cry 2',
    details: ['Action', 'FPS'],
  },
  {
    id: 15,
    image: '',
    title: 'Black & White',
    details: ['God'],
  },
  {
    id: 15,
    image: '',
    title: 'C&C: Red Alert 2',
    details: ['Fantasy', 'RTS'],
  },
  {
    id: 16,
    image: '',
    title: 'Splinter Cell: Chaos Theory',
    details: ['Stealth', 'Action', 'Adventure'],
  },
  {
    id: 17,
    image: '',
    title: 'Hitman: Blood Money',
    details: ['Stealth'],
  },
  {
    id: 18,
    image: '',
    title: 'C&C: Generals',
    details: ['Action', 'FPS'],
  },
  {
    id: 19,
    image: '',
    title: 'Max Payne',
    details: ['Neo-noir', 'Third-person', 'Shooter'],
  },
  {
    id: 20,
    image: '',
    title: 'Portal 2',
    details: ['Puzzle', 'Platform'],
  },
  {
    id: 0,
    image: '',
    title: '',
    details: ['', ''],
  },
]
